<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('category/query', [\app\bundles\category\controller\CategoryController::class, 'query']);
    Route::post('category/create', [\app\bundles\category\controller\CategoryController::class, 'create']);
    Route::get('category/show', [\app\bundles\category\controller\CategoryController::class, 'show']);
    Route::put('category/update', [\app\bundles\category\controller\CategoryController::class, 'update']);
    Route::delete('category/destroy', [\app\bundles\category\controller\CategoryController::class, 'destroy']);
});
