// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id             uint64      `json:"id"             ` //
	Name           string      `json:"name"           ` // 姓名
	Avatar         string      `json:"avatar"         ` // 头像
	Birthday       *gtime.Time `json:"birthday"       ` // 生日
	JobTitle       string      `json:"jobTitle"       ` // 职称
	IdentityNumber string      `json:"identityNumber" ` // 身份证号码
	EmployeeNumber string      `json:"employeeNumber" ` // 员工号码
	Status         int         `json:"status"         ` // 状态
	CreateUserId   uint64      `json:"createUserId"   ` //
	CreateTime     *gtime.Time `json:"createTime"     ` //
	UpdateUserId   uint64      `json:"updateUserId"   ` //
	UpdateTime     *gtime.Time `json:"updateTime"     ` //
	DeleteUserId   uint64      `json:"deleteUserId"   ` //
	DeleteTime     *gtime.Time `json:"deleteTime"     ` //
}
