<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('comment/query', [\app\bundles\comment\controller\CommentController::class, 'query']);
    Route::post('comment/create', [\app\bundles\comment\controller\CommentController::class, 'create']);
    Route::get('comment/show', [\app\bundles\comment\controller\CommentController::class, 'show']);
    Route::put('comment/update', [\app\bundles\comment\controller\CommentController::class, 'update']);
    Route::delete('comment/destroy', [\app\bundles\comment\controller\CommentController::class, 'destroy']);
});
