<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('admin', function () {
    Route::post('login', [\app\api\admin\controller\AuthController::class, 'login']);
    Route::post('forget', [\app\api\admin\controller\AuthController::class, 'forget']);
    Route::post('reset', [\app\api\admin\controller\AuthController::class, 'reset']);
});
