<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('attachmentCategory/query', [\app\bundles\attachment\controller\AttachmentCategoryController::class, 'query']);
    Route::post('attachmentCategory/create', [\app\bundles\attachment\controller\AttachmentCategoryController::class, 'create']);
    Route::get('attachmentCategory/show', [\app\bundles\attachment\controller\AttachmentCategoryController::class, 'show']);
    Route::put('attachmentCategory/update', [\app\bundles\attachment\controller\AttachmentCategoryController::class, 'update']);
    Route::delete('attachmentCategory/destroy', [\app\bundles\attachment\controller\AttachmentCategoryController::class, 'destroy']);
    Route::post('attachment/query', [\app\bundles\attachment\controller\AttachmentController::class, 'query']);
    Route::post('attachment/create', [\app\bundles\attachment\controller\AttachmentController::class, 'create']);
    Route::get('attachment/show', [\app\bundles\attachment\controller\AttachmentController::class, 'show']);
    Route::put('attachment/update', [\app\bundles\attachment\controller\AttachmentController::class, 'update']);
    Route::delete('attachment/destroy', [\app\bundles\attachment\controller\AttachmentController::class, 'destroy']);
});
