<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('tag/query', [\app\bundles\tag\controller\TagController::class, 'query']);
    Route::post('tag/create', [\app\bundles\tag\controller\TagController::class, 'create']);
    Route::get('tag/show', [\app\bundles\tag\controller\TagController::class, 'show']);
    Route::put('tag/update', [\app\bundles\tag\controller\TagController::class, 'update']);
    Route::delete('tag/destroy', [\app\bundles\tag\controller\TagController::class, 'destroy']);
});
