// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"gosoft/cms/system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ad",
				Handler: AdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/nav",
				Handler: NavHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/permission",
				Handler: PermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/privilege/:userId",
				Handler: PrivilegeHandler(serverCtx),
			},
		},
	)
}
