<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('link/query', [\app\bundles\link\controller\LinkController::class, 'query']);
    Route::post('link/create', [\app\bundles\link\controller\LinkController::class, 'create']);
    Route::get('link/show', [\app\bundles\link\controller\LinkController::class, 'show']);
    Route::put('link/update', [\app\bundles\link\controller\LinkController::class, 'update']);
    Route::delete('link/destroy', [\app\bundles\link\controller\LinkController::class, 'destroy']);
});
