<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('like/query', [\app\bundles\like\controller\LikeController::class, 'query']);
    Route::post('like/create', [\app\bundles\like\controller\LikeController::class, 'create']);
    Route::get('like/show', [\app\bundles\like\controller\LikeController::class, 'show']);
    Route::put('like/update', [\app\bundles\like\controller\LikeController::class, 'update']);
    Route::delete('like/destroy', [\app\bundles\like\controller\LikeController::class, 'destroy']);
});
