<?php

declare(strict_types=1);

namespace app\bundles\article\request\article;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'ArticleUpdateRequest',
    required: [
        'id',
        'category_id',
        'user_id',
        'title',
        'slug',
        'summary',
        'content',
        'cover_image',
        'images',
        'view_count',
        'like_count',
        'comment_count',
        'is_recommend',
        'is_top',
        'is_hot',
        'publish_status',
        'publish_time',
        'seo_title',
        'seo_keywords',
        'seo_description',
        'sort',
        'template',
        'deleted',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: 'ID', type: 'integer'),
        new OA\Property(property: 'category_id', description: '分类ID', type: 'integer'),
        new OA\Property(property: 'user_id', description: '作者ID', type: 'integer'),
        new OA\Property(property: 'title', description: '文章标题', type: 'string'),
        new OA\Property(property: 'slug', description: '文章别名', type: 'string'),
        new OA\Property(property: 'summary', description: '文章摘要', type: 'string'),
        new OA\Property(property: 'content', description: '文章内容', type: 'string'),
        new OA\Property(property: 'cover_image', description: '封面图', type: 'string'),
        new OA\Property(property: 'images', description: '图片集(JSON)', type: 'string'),
        new OA\Property(property: 'view_count', description: '浏览次数', type: 'integer'),
        new OA\Property(property: 'like_count', description: '点赞次数', type: 'integer'),
        new OA\Property(property: 'comment_count', description: '评论次数', type: 'integer'),
        new OA\Property(property: 'is_recommend', description: '是否推荐: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'is_top', description: '是否置顶: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'is_hot', description: '是否热门: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'publish_status', description: '发布状态: 1-草稿;2-已发布;3-下架', type: 'integer'),
        new OA\Property(property: 'publish_time', description: '发布时间', type: 'string'),
        new OA\Property(property: 'seo_title', description: 'SEO标题', type: 'string'),
        new OA\Property(property: 'seo_keywords', description: 'SEO关键词', type: 'string'),
        new OA\Property(property: 'seo_description', description: 'SEO描述', type: 'string'),
        new OA\Property(property: 'sort', description: '排序', type: 'integer'),
        new OA\Property(property: 'template', description: '模板', type: 'string'),
        new OA\Property(property: 'deleted', description: '删除状态: 0-未删除;1-已删除', type: 'integer'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class ArticleUpdateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'category_id' => 'require',
        'user_id' => 'require',
        'title' => 'require',
        'slug' => 'require',
        'summary' => 'require',
        'content' => 'require',
        'cover_image' => 'require',
        'images' => 'require',
        'view_count' => 'require',
        'like_count' => 'require',
        'comment_count' => 'require',
        'is_recommend' => 'require',
        'is_top' => 'require',
        'is_hot' => 'require',
        'publish_status' => 'require',
        'publish_time' => 'require',
        'seo_title' => 'require',
        'seo_keywords' => 'require',
        'seo_description' => 'require',
        'sort' => 'require',
        'template' => 'require',
        'deleted' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置ID',
        'category_id.require' => '请设置分类ID',
        'user_id.require' => '请设置作者ID',
        'title.require' => '请设置文章标题',
        'slug.require' => '请设置文章别名',
        'summary.require' => '请设置文章摘要',
        'content.require' => '请设置文章内容',
        'cover_image.require' => '请设置封面图',
        'images.require' => '请设置图片集(JSON)',
        'view_count.require' => '请设置浏览次数',
        'like_count.require' => '请设置点赞次数',
        'comment_count.require' => '请设置评论次数',
        'is_recommend.require' => '请设置是否推荐: 0-否;1-是',
        'is_top.require' => '请设置是否置顶: 0-否;1-是',
        'is_hot.require' => '请设置是否热门: 0-否;1-是',
        'publish_status.require' => '请设置发布状态: 1-草稿;2-已发布;3-下架',
        'publish_time.require' => '请设置发布时间',
        'seo_title.require' => '请设置SEO标题',
        'seo_keywords.require' => '请设置SEO关键词',
        'seo_description.require' => '请设置SEO描述',
        'sort.require' => '请设置排序',
        'template.require' => '请设置模板',
        'deleted.require' => '请设置删除状态: 0-未删除;1-已删除',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
