<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('operationLog/query', [\app\bundles\operation\controller\OperationLogController::class, 'query']);
    Route::post('operationLog/create', [\app\bundles\operation\controller\OperationLogController::class, 'create']);
    Route::get('operationLog/show', [\app\bundles\operation\controller\OperationLogController::class, 'show']);
    Route::put('operationLog/update', [\app\bundles\operation\controller\OperationLogController::class, 'update']);
    Route::delete('operationLog/destroy', [\app\bundles\operation\controller\OperationLogController::class, 'destroy']);
});
