<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('page/query', [\app\bundles\page\controller\PageController::class, 'query']);
    Route::post('page/create', [\app\bundles\page\controller\PageController::class, 'create']);
    Route::get('page/show', [\app\bundles\page\controller\PageController::class, 'show']);
    Route::put('page/update', [\app\bundles\page\controller\PageController::class, 'update']);
    Route::delete('page/destroy', [\app\bundles\page\controller\PageController::class, 'destroy']);
});
