<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('user/query', [\app\bundles\user\controller\UserController::class, 'query']);
    Route::post('user/create', [\app\bundles\user\controller\UserController::class, 'create']);
    Route::get('user/show', [\app\bundles\user\controller\UserController::class, 'show']);
    Route::put('user/update', [\app\bundles\user\controller\UserController::class, 'update']);
    Route::delete('user/destroy', [\app\bundles\user\controller\UserController::class, 'destroy']);
});
