<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('favorite/query', [\app\bundles\favorite\controller\FavoriteController::class, 'query']);
    Route::post('favorite/create', [\app\bundles\favorite\controller\FavoriteController::class, 'create']);
    Route::get('favorite/show', [\app\bundles\favorite\controller\FavoriteController::class, 'show']);
    Route::put('favorite/update', [\app\bundles\favorite\controller\FavoriteController::class, 'update']);
    Route::delete('favorite/destroy', [\app\bundles\favorite\controller\FavoriteController::class, 'destroy']);
});
