// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IAdminAuth interface {
	Login(id int) int
}

var localAdminAuth IAdminAuth

func AdminAuth() IAdminAuth {
	if localAdminAuth == nil {
		panic("implement not found for interface IAdminAuth, forgot register?")
	}
	return localAdminAuth
}

func RegisterAdminAuth(i IAdminAuth) {
	localAdminAuth = i
}
