// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package mobile

import (
	"gitee.com/gosoft/gomall/internal/api/mobile"
)

type ControllerV1 struct{}

func NewV1() mobile.IMobileV1 {
	return &ControllerV1{}
}
