// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAccountLogDao is internal type for wrapping internal DAO implements.
type internalAccountLogDao = *internal.AccountLogDao

// accountLogDao is the data access object for table account_log.
// You can define custom methods on it to extend its functionality as you wish.
type accountLogDao struct {
	internalAccountLogDao
}

var (
	// AccountLog is globally public accessible object for table account_log operations.
	AccountLog = accountLogDao{
		internal.NewAccountLogDao(),
	}
)

// Fill with you ideas below.
