// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAdDao is internal type for wrapping internal DAO implements.
type internalAdDao = *internal.AdDao

// adDao is the data access object for table ad.
// You can define custom methods on it to extend its functionality as you wish.
type adDao struct {
	internalAdDao
}

var (
	// Ad is globally public accessible object for table ad operations.
	Ad = adDao{
		internal.NewAdDao(),
	}
)

// Fill with you ideas below.
