// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalAdCustomDao is internal type for wrapping internal DAO implements.
type internalAdCustomDao = *internal.AdCustomDao

// adCustomDao is the data access object for table ad_custom.
// You can define custom methods on it to extend its functionality as you wish.
type adCustomDao struct {
	internalAdCustomDao
}

var (
	// AdCustom is globally public accessible object for table ad_custom operations.
	AdCustom = adCustomDao{
		internal.NewAdCustomDao(),
	}
)

// Fill with you ideas below.
