// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAdPositionDao is internal type for wrapping internal DAO implements.
type internalAdPositionDao = *internal.AdPositionDao

// adPositionDao is the data access object for table ad_position.
// You can define custom methods on it to extend its functionality as you wish.
type adPositionDao struct {
	internalAdPositionDao
}

var (
	// AdPosition is globally public accessible object for table ad_position operations.
	AdPosition = adPositionDao{
		internal.NewAdPositionDao(),
	}
)

// Fill with you ideas below.
