// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalAdminActionDao is internal type for wrapping internal DAO implements.
type internalAdminActionDao = *internal.AdminActionDao

// adminActionDao is the data access object for table admin_action.
// You can define custom methods on it to extend its functionality as you wish.
type adminActionDao struct {
	internalAdminActionDao
}

var (
	// AdminAction is globally public accessible object for table admin_action operations.
	AdminAction = adminActionDao{
		internal.NewAdminActionDao(),
	}
)

// Fill with you ideas below.
