// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAdminMessageDao is internal type for wrapping internal DAO implements.
type internalAdminMessageDao = *internal.AdminMessageDao

// adminMessageDao is the data access object for table admin_message.
// You can define custom methods on it to extend its functionality as you wish.
type adminMessageDao struct {
	internalAdminMessageDao
}

var (
	// AdminMessage is globally public accessible object for table admin_message operations.
	AdminMessage = adminMessageDao{
		internal.NewAdminMessageDao(),
	}
)

// Fill with you ideas below.
