// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAdminLogDao is internal type for wrapping internal DAO implements.
type internalAdminLogDao = *internal.AdminLogDao

// adminLogDao is the data access object for table admin_log.
// You can define custom methods on it to extend its functionality as you wish.
type adminLogDao struct {
	internalAdminLogDao
}

var (
	// AdminLog is globally public accessible object for table admin_log operations.
	AdminLog = adminLogDao{
		internal.NewAdminLogDao(),
	}
)

// Fill with you ideas below.
