// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAdsenseDao is internal type for wrapping internal DAO implements.
type internalAdsenseDao = *internal.AdsenseDao

// adsenseDao is the data access object for table adsense.
// You can define custom methods on it to extend its functionality as you wish.
type adsenseDao struct {
	internalAdsenseDao
}

var (
	// Adsense is globally public accessible object for table adsense operations.
	Adsense = adsenseDao{
		internal.NewAdsenseDao(),
	}
)

// Fill with you ideas below.
