// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalAffiliateLogDao is internal type for wrapping internal DAO implements.
type internalAffiliateLogDao = *internal.AffiliateLogDao

// affiliateLogDao is the data access object for table affiliate_log.
// You can define custom methods on it to extend its functionality as you wish.
type affiliateLogDao struct {
	internalAffiliateLogDao
}

var (
	// AffiliateLog is globally public accessible object for table affiliate_log operations.
	AffiliateLog = affiliateLogDao{
		internal.NewAffiliateLogDao(),
	}
)

// Fill with you ideas below.
