// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalAgencyDao is internal type for wrapping internal DAO implements.
type internalAgencyDao = *internal.AgencyDao

// agencyDao is the data access object for table agency.
// You can define custom methods on it to extend its functionality as you wish.
type agencyDao struct {
	internalAgencyDao
}

var (
	// Agency is globally public accessible object for table agency operations.
	Agency = agencyDao{
		internal.NewAgencyDao(),
	}
)

// Fill with you ideas below.
