// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAreaRegionDao is internal type for wrapping internal DAO implements.
type internalAreaRegionDao = *internal.AreaRegionDao

// areaRegionDao is the data access object for table area_region.
// You can define custom methods on it to extend its functionality as you wish.
type areaRegionDao struct {
	internalAreaRegionDao
}

var (
	// AreaRegion is globally public accessible object for table area_region operations.
	AreaRegion = areaRegionDao{
		internal.NewAreaRegionDao(),
	}
)

// Fill with you ideas below.
