// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalArticleCatDao is internal type for wrapping internal DAO implements.
type internalArticleCatDao = *internal.ArticleCatDao

// articleCatDao is the data access object for table article_cat.
// You can define custom methods on it to extend its functionality as you wish.
type articleCatDao struct {
	internalArticleCatDao
}

var (
	// ArticleCat is globally public accessible object for table article_cat operations.
	ArticleCat = articleCatDao{
		internal.NewArticleCatDao(),
	}
)

// Fill with you ideas below.
