// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalAttributeDao is internal type for wrapping internal DAO implements.
type internalAttributeDao = *internal.AttributeDao

// attributeDao is the data access object for table attribute.
// You can define custom methods on it to extend its functionality as you wish.
type attributeDao struct {
	internalAttributeDao
}

var (
	// Attribute is globally public accessible object for table attribute operations.
	Attribute = attributeDao{
		internal.NewAttributeDao(),
	}
)

// Fill with you ideas below.
