// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalAutoManageDao is internal type for wrapping internal DAO implements.
type internalAutoManageDao = *internal.AutoManageDao

// autoManageDao is the data access object for table auto_manage.
// You can define custom methods on it to extend its functionality as you wish.
type autoManageDao struct {
	internalAutoManageDao
}

var (
	// AutoManage is globally public accessible object for table auto_manage operations.
	AutoManage = autoManageDao{
		internal.NewAutoManageDao(),
	}
)

// Fill with you ideas below.
