// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalBackGoodsDao is internal type for wrapping internal DAO implements.
type internalBackGoodsDao = *internal.BackGoodsDao

// backGoodsDao is the data access object for table back_goods.
// You can define custom methods on it to extend its functionality as you wish.
type backGoodsDao struct {
	internalBackGoodsDao
}

var (
	// BackGoods is globally public accessible object for table back_goods operations.
	BackGoods = backGoodsDao{
		internal.NewBackGoodsDao(),
	}
)

// Fill with you ideas below.
