// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalBackOrderDao is internal type for wrapping internal DAO implements.
type internalBackOrderDao = *internal.BackOrderDao

// backOrderDao is the data access object for table back_order.
// You can define custom methods on it to extend its functionality as you wish.
type backOrderDao struct {
	internalBackOrderDao
}

var (
	// BackOrder is globally public accessible object for table back_order operations.
	BackOrder = backOrderDao{
		internal.NewBackOrderDao(),
	}
)

// Fill with you ideas below.
