// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalBonusTypeDao is internal type for wrapping internal DAO implements.
type internalBonusTypeDao = *internal.BonusTypeDao

// bonusTypeDao is the data access object for table bonus_type.
// You can define custom methods on it to extend its functionality as you wish.
type bonusTypeDao struct {
	internalBonusTypeDao
}

var (
	// BonusType is globally public accessible object for table bonus_type operations.
	BonusType = bonusTypeDao{
		internal.NewBonusTypeDao(),
	}
)

// Fill with you ideas below.
