// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalBookingGoodsDao is internal type for wrapping internal DAO implements.
type internalBookingGoodsDao = *internal.BookingGoodsDao

// bookingGoodsDao is the data access object for table booking_goods.
// You can define custom methods on it to extend its functionality as you wish.
type bookingGoodsDao struct {
	internalBookingGoodsDao
}

var (
	// BookingGoods is globally public accessible object for table booking_goods operations.
	BookingGoods = bookingGoodsDao{
		internal.NewBookingGoodsDao(),
	}
)

// Fill with you ideas below.
