// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalCardDao is internal type for wrapping internal DAO implements.
type internalCardDao = *internal.CardDao

// cardDao is the data access object for table card.
// You can define custom methods on it to extend its functionality as you wish.
type cardDao struct {
	internalCardDao
}

var (
	// Card is globally public accessible object for table card operations.
	Card = cardDao{
		internal.NewCardDao(),
	}
)

// Fill with you ideas below.
