// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalCatRecommendDao is internal type for wrapping internal DAO implements.
type internalCatRecommendDao = *internal.CatRecommendDao

// catRecommendDao is the data access object for table cat_recommend.
// You can define custom methods on it to extend its functionality as you wish.
type catRecommendDao struct {
	internalCatRecommendDao
}

var (
	// CatRecommend is globally public accessible object for table cat_recommend operations.
	CatRecommend = catRecommendDao{
		internal.NewCatRecommendDao(),
	}
)

// Fill with you ideas below.
