// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalCronsDao is internal type for wrapping internal DAO implements.
type internalCronsDao = *internal.CronsDao

// cronsDao is the data access object for table crons.
// You can define custom methods on it to extend its functionality as you wish.
type cronsDao struct {
	internalCronsDao
}

var (
	// Crons is globally public accessible object for table crons operations.
	Crons = cronsDao{
		internal.NewCronsDao(),
	}
)

// Fill with you ideas below.
