// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalDeliveryGoodsDao is internal type for wrapping internal DAO implements.
type internalDeliveryGoodsDao = *internal.DeliveryGoodsDao

// deliveryGoodsDao is the data access object for table delivery_goods.
// You can define custom methods on it to extend its functionality as you wish.
type deliveryGoodsDao struct {
	internalDeliveryGoodsDao
}

var (
	// DeliveryGoods is globally public accessible object for table delivery_goods operations.
	DeliveryGoods = deliveryGoodsDao{
		internal.NewDeliveryGoodsDao(),
	}
)

// Fill with you ideas below.
