// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalDeliveryOrderDao is internal type for wrapping internal DAO implements.
type internalDeliveryOrderDao = *internal.DeliveryOrderDao

// deliveryOrderDao is the data access object for table delivery_order.
// You can define custom methods on it to extend its functionality as you wish.
type deliveryOrderDao struct {
	internalDeliveryOrderDao
}

var (
	// DeliveryOrder is globally public accessible object for table delivery_order operations.
	DeliveryOrder = deliveryOrderDao{
		internal.NewDeliveryOrderDao(),
	}
)

// Fill with you ideas below.
