// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalEmailListDao is internal type for wrapping internal DAO implements.
type internalEmailListDao = *internal.EmailListDao

// emailListDao is the data access object for table email_list.
// You can define custom methods on it to extend its functionality as you wish.
type emailListDao struct {
	internalEmailListDao
}

var (
	// EmailList is globally public accessible object for table email_list operations.
	EmailList = emailListDao{
		internal.NewEmailListDao(),
	}
)

// Fill with you ideas below.
