// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalExchangeGoodsDao is internal type for wrapping internal DAO implements.
type internalExchangeGoodsDao = *internal.ExchangeGoodsDao

// exchangeGoodsDao is the data access object for table exchange_goods.
// You can define custom methods on it to extend its functionality as you wish.
type exchangeGoodsDao struct {
	internalExchangeGoodsDao
}

var (
	// ExchangeGoods is globally public accessible object for table exchange_goods operations.
	ExchangeGoods = exchangeGoodsDao{
		internal.NewExchangeGoodsDao(),
	}
)

// Fill with you ideas below.
