// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalFavourableActivityDao is internal type for wrapping internal DAO implements.
type internalFavourableActivityDao = *internal.FavourableActivityDao

// favourableActivityDao is the data access object for table favourable_activity.
// You can define custom methods on it to extend its functionality as you wish.
type favourableActivityDao struct {
	internalFavourableActivityDao
}

var (
	// FavourableActivity is globally public accessible object for table favourable_activity operations.
	FavourableActivity = favourableActivityDao{
		internal.NewFavourableActivityDao(),
	}
)

// Fill with you ideas below.
