// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalFriendLinkDao is internal type for wrapping internal DAO implements.
type internalFriendLinkDao = *internal.FriendLinkDao

// friendLinkDao is the data access object for table friend_link.
// You can define custom methods on it to extend its functionality as you wish.
type friendLinkDao struct {
	internalFriendLinkDao
}

var (
	// FriendLink is globally public accessible object for table friend_link operations.
	FriendLink = friendLinkDao{
		internal.NewFriendLinkDao(),
	}
)

// Fill with you ideas below.
