// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalGoodsTypeDao is internal type for wrapping internal DAO implements.
type internalGoodsTypeDao = *internal.GoodsTypeDao

// goodsTypeDao is the data access object for table goods_type.
// You can define custom methods on it to extend its functionality as you wish.
type goodsTypeDao struct {
	internalGoodsTypeDao
}

var (
	// GoodsType is globally public accessible object for table goods_type operations.
	GoodsType = goodsTypeDao{
		internal.NewGoodsTypeDao(),
	}
)

// Fill with you ideas below.
