// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalGoodsActivityDao is internal type for wrapping internal DAO implements.
type internalGoodsActivityDao = *internal.GoodsActivityDao

// goodsActivityDao is the data access object for table goods_activity.
// You can define custom methods on it to extend its functionality as you wish.
type goodsActivityDao struct {
	internalGoodsActivityDao
}

var (
	// GoodsActivity is globally public accessible object for table goods_activity operations.
	GoodsActivity = goodsActivityDao{
		internal.NewGoodsActivityDao(),
	}
)

// Fill with you ideas below.
