// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalGoodsCatDao is internal type for wrapping internal DAO implements.
type internalGoodsCatDao = *internal.GoodsCatDao

// goodsCatDao is the data access object for table goods_cat.
// You can define custom methods on it to extend its functionality as you wish.
type goodsCatDao struct {
	internalGoodsCatDao
}

var (
	// GoodsCat is globally public accessible object for table goods_cat operations.
	GoodsCat = goodsCatDao{
		internal.NewGoodsCatDao(),
	}
)

// Fill with you ideas below.
