// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalGoodsArticleDao is internal type for wrapping internal DAO implements.
type internalGoodsArticleDao = *internal.GoodsArticleDao

// goodsArticleDao is the data access object for table goods_article.
// You can define custom methods on it to extend its functionality as you wish.
type goodsArticleDao struct {
	internalGoodsArticleDao
}

var (
	// GoodsArticle is globally public accessible object for table goods_article operations.
	GoodsArticle = goodsArticleDao{
		internal.NewGoodsArticleDao(),
	}
)

// Fill with you ideas below.
