// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalGoodsGalleryDao is internal type for wrapping internal DAO implements.
type internalGoodsGalleryDao = *internal.GoodsGalleryDao

// goodsGalleryDao is the data access object for table goods_gallery.
// You can define custom methods on it to extend its functionality as you wish.
type goodsGalleryDao struct {
	internalGoodsGalleryDao
}

var (
	// GoodsGallery is globally public accessible object for table goods_gallery operations.
	GoodsGallery = goodsGalleryDao{
		internal.NewGoodsGalleryDao(),
	}
)

// Fill with you ideas below.
