// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalGoodsAttrDao is internal type for wrapping internal DAO implements.
type internalGoodsAttrDao = *internal.GoodsAttrDao

// goodsAttrDao is the data access object for table goods_attr.
// You can define custom methods on it to extend its functionality as you wish.
type goodsAttrDao struct {
	internalGoodsAttrDao
}

var (
	// GoodsAttr is globally public accessible object for table goods_attr operations.
	GoodsAttr = goodsAttrDao{
		internal.NewGoodsAttrDao(),
	}
)

// Fill with you ideas below.
