// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalKeywordsDao is internal type for wrapping internal DAO implements.
type internalKeywordsDao = *internal.KeywordsDao

// keywordsDao is the data access object for table keywords.
// You can define custom methods on it to extend its functionality as you wish.
type keywordsDao struct {
	internalKeywordsDao
}

var (
	// Keywords is globally public accessible object for table keywords operations.
	Keywords = keywordsDao{
		internal.NewKeywordsDao(),
	}
)

// Fill with you ideas below.
