// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalLinkGoodsDao is internal type for wrapping internal DAO implements.
type internalLinkGoodsDao = *internal.LinkGoodsDao

// linkGoodsDao is the data access object for table link_goods.
// You can define custom methods on it to extend its functionality as you wish.
type linkGoodsDao struct {
	internalLinkGoodsDao
}

var (
	// LinkGoods is globally public accessible object for table link_goods operations.
	LinkGoods = linkGoodsDao{
		internal.NewLinkGoodsDao(),
	}
)

// Fill with you ideas below.
