// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalMailTemplatesDao is internal type for wrapping internal DAO implements.
type internalMailTemplatesDao = *internal.MailTemplatesDao

// mailTemplatesDao is the data access object for table mail_templates.
// You can define custom methods on it to extend its functionality as you wish.
type mailTemplatesDao struct {
	internalMailTemplatesDao
}

var (
	// MailTemplates is globally public accessible object for table mail_templates operations.
	MailTemplates = mailTemplatesDao{
		internal.NewMailTemplatesDao(),
	}
)

// Fill with you ideas below.
