// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalMemberPriceDao is internal type for wrapping internal DAO implements.
type internalMemberPriceDao = *internal.MemberPriceDao

// memberPriceDao is the data access object for table member_price.
// You can define custom methods on it to extend its functionality as you wish.
type memberPriceDao struct {
	internalMemberPriceDao
}

var (
	// MemberPrice is globally public accessible object for table member_price operations.
	MemberPrice = memberPriceDao{
		internal.NewMemberPriceDao(),
	}
)

// Fill with you ideas below.
