// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalNavDao is internal type for wrapping internal DAO implements.
type internalNavDao = *internal.NavDao

// navDao is the data access object for table nav.
// You can define custom methods on it to extend its functionality as you wish.
type navDao struct {
	internalNavDao
}

var (
	// Nav is globally public accessible object for table nav operations.
	Nav = navDao{
		internal.NewNavDao(),
	}
)

// Fill with you ideas below.
