// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalOrderGoodsDao is internal type for wrapping internal DAO implements.
type internalOrderGoodsDao = *internal.OrderGoodsDao

// orderGoodsDao is the data access object for table order_goods.
// You can define custom methods on it to extend its functionality as you wish.
type orderGoodsDao struct {
	internalOrderGoodsDao
}

var (
	// OrderGoods is globally public accessible object for table order_goods operations.
	OrderGoods = orderGoodsDao{
		internal.NewOrderGoodsDao(),
	}
)

// Fill with you ideas below.
