// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalOrderActionDao is internal type for wrapping internal DAO implements.
type internalOrderActionDao = *internal.OrderActionDao

// orderActionDao is the data access object for table order_action.
// You can define custom methods on it to extend its functionality as you wish.
type orderActionDao struct {
	internalOrderActionDao
}

var (
	// OrderAction is globally public accessible object for table order_action operations.
	OrderAction = orderActionDao{
		internal.NewOrderActionDao(),
	}
)

// Fill with you ideas below.
