// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalPackDao is internal type for wrapping internal DAO implements.
type internalPackDao = *internal.PackDao

// packDao is the data access object for table pack.
// You can define custom methods on it to extend its functionality as you wish.
type packDao struct {
	internalPackDao
}

var (
	// Pack is globally public accessible object for table pack operations.
	Pack = packDao{
		internal.NewPackDao(),
	}
)

// Fill with you ideas below.
