// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalPackageGoodsDao is internal type for wrapping internal DAO implements.
type internalPackageGoodsDao = *internal.PackageGoodsDao

// packageGoodsDao is the data access object for table package_goods.
// You can define custom methods on it to extend its functionality as you wish.
type packageGoodsDao struct {
	internalPackageGoodsDao
}

var (
	// PackageGoods is globally public accessible object for table package_goods operations.
	PackageGoods = packageGoodsDao{
		internal.NewPackageGoodsDao(),
	}
)

// Fill with you ideas below.
