// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalPluginsDao is internal type for wrapping internal DAO implements.
type internalPluginsDao = *internal.PluginsDao

// pluginsDao is the data access object for table plugins.
// You can define custom methods on it to extend its functionality as you wish.
type pluginsDao struct {
	internalPluginsDao
}

var (
	// Plugins is globally public accessible object for table plugins operations.
	Plugins = pluginsDao{
		internal.NewPluginsDao(),
	}
)

// Fill with you ideas below.
