// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalRegExtendInfoDao is internal type for wrapping internal DAO implements.
type internalRegExtendInfoDao = *internal.RegExtendInfoDao

// regExtendInfoDao is the data access object for table reg_extend_info.
// You can define custom methods on it to extend its functionality as you wish.
type regExtendInfoDao struct {
	internalRegExtendInfoDao
}

var (
	// RegExtendInfo is globally public accessible object for table reg_extend_info operations.
	RegExtendInfo = regExtendInfoDao{
		internal.NewRegExtendInfoDao(),
	}
)

// Fill with you ideas below.
