// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalRegFieldsDao is internal type for wrapping internal DAO implements.
type internalRegFieldsDao = *internal.RegFieldsDao

// regFieldsDao is the data access object for table reg_fields.
// You can define custom methods on it to extend its functionality as you wish.
type regFieldsDao struct {
	internalRegFieldsDao
}

var (
	// RegFields is globally public accessible object for table reg_fields operations.
	RegFields = regFieldsDao{
		internal.NewRegFieldsDao(),
	}
)

// Fill with you ideas below.
