// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalRegionDao is internal type for wrapping internal DAO implements.
type internalRegionDao = *internal.RegionDao

// regionDao is the data access object for table region.
// You can define custom methods on it to extend its functionality as you wish.
type regionDao struct {
	internalRegionDao
}

var (
	// Region is globally public accessible object for table region operations.
	Region = regionDao{
		internal.NewRegionDao(),
	}
)

// Fill with you ideas below.
