// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalSearchengineDao is internal type for wrapping internal DAO implements.
type internalSearchengineDao = *internal.SearchengineDao

// searchengineDao is the data access object for table searchengine.
// You can define custom methods on it to extend its functionality as you wish.
type searchengineDao struct {
	internalSearchengineDao
}

var (
	// Searchengine is globally public accessible object for table searchengine operations.
	Searchengine = searchengineDao{
		internal.NewSearchengineDao(),
	}
)

// Fill with you ideas below.
