// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalShippingDao is internal type for wrapping internal DAO implements.
type internalShippingDao = *internal.ShippingDao

// shippingDao is the data access object for table shipping.
// You can define custom methods on it to extend its functionality as you wish.
type shippingDao struct {
	internalShippingDao
}

var (
	// Shipping is globally public accessible object for table shipping operations.
	Shipping = shippingDao{
		internal.NewShippingDao(),
	}
)

// Fill with you ideas below.
