// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalShopConfigDao is internal type for wrapping internal DAO implements.
type internalShopConfigDao = *internal.ShopConfigDao

// shopConfigDao is the data access object for table shop_config.
// You can define custom methods on it to extend its functionality as you wish.
type shopConfigDao struct {
	internalShopConfigDao
}

var (
	// ShopConfig is globally public accessible object for table shop_config operations.
	ShopConfig = shopConfigDao{
		internal.NewShopConfigDao(),
	}
)

// Fill with you ideas below.
