// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalSnatchLogDao is internal type for wrapping internal DAO implements.
type internalSnatchLogDao = *internal.SnatchLogDao

// snatchLogDao is the data access object for table snatch_log.
// You can define custom methods on it to extend its functionality as you wish.
type snatchLogDao struct {
	internalSnatchLogDao
}

var (
	// SnatchLog is globally public accessible object for table snatch_log operations.
	SnatchLog = snatchLogDao{
		internal.NewSnatchLogDao(),
	}
)

// Fill with you ideas below.
