// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalSuppliersDao is internal type for wrapping internal DAO implements.
type internalSuppliersDao = *internal.SuppliersDao

// suppliersDao is the data access object for table suppliers.
// You can define custom methods on it to extend its functionality as you wish.
type suppliersDao struct {
	internalSuppliersDao
}

var (
	// Suppliers is globally public accessible object for table suppliers operations.
	Suppliers = suppliersDao{
		internal.NewSuppliersDao(),
	}
)

// Fill with you ideas below.
