// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalTemplateDao is internal type for wrapping internal DAO implements.
type internalTemplateDao = *internal.TemplateDao

// templateDao is the data access object for table template.
// You can define custom methods on it to extend its functionality as you wish.
type templateDao struct {
	internalTemplateDao
}

var (
	// Template is globally public accessible object for table template operations.
	Template = templateDao{
		internal.NewTemplateDao(),
	}
)

// Fill with you ideas below.
