// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalTopicDao is internal type for wrapping internal DAO implements.
type internalTopicDao = *internal.TopicDao

// topicDao is the data access object for table topic.
// You can define custom methods on it to extend its functionality as you wish.
type topicDao struct {
	internalTopicDao
}

var (
	// Topic is globally public accessible object for table topic operations.
	Topic = topicDao{
		internal.NewTopicDao(),
	}
)

// Fill with you ideas below.
