// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalUserBonusDao is internal type for wrapping internal DAO implements.
type internalUserBonusDao = *internal.UserBonusDao

// userBonusDao is the data access object for table user_bonus.
// You can define custom methods on it to extend its functionality as you wish.
type userBonusDao struct {
	internalUserBonusDao
}

var (
	// UserBonus is globally public accessible object for table user_bonus operations.
	UserBonus = userBonusDao{
		internal.NewUserBonusDao(),
	}
)

// Fill with you ideas below.
