// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalUserAddressDao is internal type for wrapping internal DAO implements.
type internalUserAddressDao = *internal.UserAddressDao

// userAddressDao is the data access object for table user_address.
// You can define custom methods on it to extend its functionality as you wish.
type userAddressDao struct {
	internalUserAddressDao
}

var (
	// UserAddress is globally public accessible object for table user_address operations.
	UserAddress = userAddressDao{
		internal.NewUserAddressDao(),
	}
)

// Fill with you ideas below.
