// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalUserAccountDao is internal type for wrapping internal DAO implements.
type internalUserAccountDao = *internal.UserAccountDao

// userAccountDao is the data access object for table user_account.
// You can define custom methods on it to extend its functionality as you wish.
type userAccountDao struct {
	internalUserAccountDao
}

var (
	// UserAccount is globally public accessible object for table user_account operations.
	UserAccount = userAccountDao{
		internal.NewUserAccountDao(),
	}
)

// Fill with you ideas below.
