// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalUserRankDao is internal type for wrapping internal DAO implements.
type internalUserRankDao = *internal.UserRankDao

// userRankDao is the data access object for table user_rank.
// You can define custom methods on it to extend its functionality as you wish.
type userRankDao struct {
	internalUserRankDao
}

var (
	// UserRank is globally public accessible object for table user_rank operations.
	UserRank = userRankDao{
		internal.NewUserRankDao(),
	}
)

// Fill with you ideas below.
