// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalVirtualCardDao is internal type for wrapping internal DAO implements.
type internalVirtualCardDao = *internal.VirtualCardDao

// virtualCardDao is the data access object for table virtual_card.
// You can define custom methods on it to extend its functionality as you wish.
type virtualCardDao struct {
	internalVirtualCardDao
}

var (
	// VirtualCard is globally public accessible object for table virtual_card operations.
	VirtualCard = virtualCardDao{
		internal.NewVirtualCardDao(),
	}
)

// Fill with you ideas below.
