// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalVolumePriceDao is internal type for wrapping internal DAO implements.
type internalVolumePriceDao = *internal.VolumePriceDao

// volumePriceDao is the data access object for table volume_price.
// You can define custom methods on it to extend its functionality as you wish.
type volumePriceDao struct {
	internalVolumePriceDao
}

var (
	// VolumePrice is globally public accessible object for table volume_price operations.
	VolumePrice = volumePriceDao{
		internal.NewVolumePriceDao(),
	}
)

// Fill with you ideas below.
