// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalVoteLogDao is internal type for wrapping internal DAO implements.
type internalVoteLogDao = *internal.VoteLogDao

// voteLogDao is the data access object for table vote_log.
// You can define custom methods on it to extend its functionality as you wish.
type voteLogDao struct {
	internalVoteLogDao
}

var (
	// VoteLog is globally public accessible object for table vote_log operations.
	VoteLog = voteLogDao{
		internal.NewVoteLogDao(),
	}
)

// Fill with you ideas below.
