// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalVoteDao is internal type for wrapping internal DAO implements.
type internalVoteDao = *internal.VoteDao

// voteDao is the data access object for table vote.
// You can define custom methods on it to extend its functionality as you wish.
type voteDao struct {
	internalVoteDao
}

var (
	// Vote is globally public accessible object for table vote operations.
	Vote = voteDao{
		internal.NewVoteDao(),
	}
)

// Fill with you ideas below.
