// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gomall/internal/repository/internal"
)

// internalVoteOptionDao is internal type for wrapping internal DAO implements.
type internalVoteOptionDao = *internal.VoteOptionDao

// voteOptionDao is the data access object for table vote_option.
// You can define custom methods on it to extend its functionality as you wish.
type voteOptionDao struct {
	internalVoteOptionDao
}

var (
	// VoteOption is globally public accessible object for table vote_option operations.
	VoteOption = voteOptionDao{
		internal.NewVoteOptionDao(),
	}
)

// Fill with you ideas below.
