// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package repository

import (
	"gitee.com/gosoft/gomall/internal/repository/internal"
)

// internalWholesaleDao is internal type for wrapping internal DAO implements.
type internalWholesaleDao = *internal.WholesaleDao

// wholesaleDao is the data access object for table wholesale.
// You can define custom methods on it to extend its functionality as you wish.
type wholesaleDao struct {
	internalWholesaleDao
}

var (
	// Wholesale is globally public accessible object for table wholesale operations.
	Wholesale = wholesaleDao{
		internal.NewWholesaleDao(),
	}
)

// Fill with you ideas below.
