<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('notification/query', [\app\bundles\notification\controller\NotificationController::class, 'query']);
    Route::post('notification/create', [\app\bundles\notification\controller\NotificationController::class, 'create']);
    Route::get('notification/show', [\app\bundles\notification\controller\NotificationController::class, 'show']);
    Route::put('notification/update', [\app\bundles\notification\controller\NotificationController::class, 'update']);
    Route::delete('notification/destroy', [\app\bundles\notification\controller\NotificationController::class, 'destroy']);
});
