app:
  name: Gin
  debug: true

server:
  port: 8008

logging:
  level: debug

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

redis:
  host: 127.0.0.1
  port: 6379
  username: root
  password: root
  database: 0

cache:
  database: 1
  prefix:
