<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('user', function () {
    Route::post('login', [\app\api\user\controller\AuthController::class, 'login']);
    Route::post('forget', [\app\api\user\controller\AuthController::class, 'forget']);
    Route::post('reset', [\app\api\user\controller\AuthController::class, 'reset']);
    Route::get('dashboard', [\app\api\user\controller\IndexController::class, 'index']);
});
