// Code generated by goctl. DO NOT EDIT.
package types

type AdReq struct {
	Name string `json:"name"`
}

type AdRes struct {
}

type NavReq struct {
	Name string `json:"name"`
}

type NavRes struct {
}

type PermissionReq struct {
	Name string `json:"name"`
}

type PermissionRes struct {
}

type PrivilegeReq struct {
	Name string `json:"name"`
}

type PrivilegeRes struct {
}
