<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('common', function () {
    Route::get('captcha/image', [\app\api\common\controller\CaptchaController::class, 'image']);
    Route::post('sms/send', [\app\api\common\controller\SmsController::class, 'send']);
});
