// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta         `orm:"table:user, do:true"`
	Id             interface{} //
	Name           interface{} // 姓名
	Avatar         interface{} // 头像
	Birthday       *gtime.Time // 生日
	JobTitle       interface{} // 职称
	IdentityNumber interface{} // 身份证号码
	EmployeeNumber interface{} // 员工号码
	Status         interface{} // 状态
	CreateUserId   interface{} //
	CreateTime     *gtime.Time //
	UpdateUserId   interface{} //
	UpdateTime     *gtime.Time //
	DeleteUserId   interface{} //
	DeleteTime     *gtime.Time //
}
