// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package supplier

import (
	"gitee.com/gosoft/gomall/internal/app/supplier"
)

type ControllerV1 struct{}

func NewV1() supplier.ISupplierV1 {
	return &ControllerV1{}
}
