<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('loginLog/query', [\app\bundles\login\controller\LoginLogController::class, 'query']);
    Route::post('loginLog/create', [\app\bundles\login\controller\LoginLogController::class, 'create']);
    Route::get('loginLog/show', [\app\bundles\login\controller\LoginLogController::class, 'show']);
    Route::put('loginLog/update', [\app\bundles\login\controller\LoginLogController::class, 'update']);
    Route::delete('loginLog/destroy', [\app\bundles\login\controller\LoginLogController::class, 'destroy']);
});
