<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('navigation/query', [\app\bundles\navigation\controller\NavigationController::class, 'query']);
    Route::post('navigation/create', [\app\bundles\navigation\controller\NavigationController::class, 'create']);
    Route::get('navigation/show', [\app\bundles\navigation\controller\NavigationController::class, 'show']);
    Route::put('navigation/update', [\app\bundles\navigation\controller\NavigationController::class, 'update']);
    Route::delete('navigation/destroy', [\app\bundles\navigation\controller\NavigationController::class, 'destroy']);
});
