<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('article/query', [\app\bundles\article\controller\ArticleController::class, 'query']);
    Route::post('article/create', [\app\bundles\article\controller\ArticleController::class, 'create']);
    Route::get('article/show', [\app\bundles\article\controller\ArticleController::class, 'show']);
    Route::put('article/update', [\app\bundles\article\controller\ArticleController::class, 'update']);
    Route::delete('article/destroy', [\app\bundles\article\controller\ArticleController::class, 'destroy']);
    Route::post('articleTag/query', [\app\bundles\article\controller\ArticleTagController::class, 'query']);
    Route::post('articleTag/create', [\app\bundles\article\controller\ArticleTagController::class, 'create']);
    Route::get('articleTag/show', [\app\bundles\article\controller\ArticleTagController::class, 'show']);
    Route::put('articleTag/update', [\app\bundles\article\controller\ArticleTagController::class, 'update']);
    Route::delete('articleTag/destroy', [\app\bundles\article\controller\ArticleTagController::class, 'destroy']);
});
