<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('dict/query', [\app\bundles\dict\controller\DictController::class, 'query']);
    Route::post('dict/create', [\app\bundles\dict\controller\DictController::class, 'create']);
    Route::get('dict/show', [\app\bundles\dict\controller\DictController::class, 'show']);
    Route::put('dict/update', [\app\bundles\dict\controller\DictController::class, 'update']);
    Route::delete('dict/destroy', [\app\bundles\dict\controller\DictController::class, 'destroy']);
});
