// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package store

import (
	"gomall/internal/api/store"
)

type ControllerV1 struct{}

func NewV1() store.IStoreV1 {
	return &ControllerV1{}
}
