// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package seller

import (
	"gomall/internal/api/seller"
)

type ControllerV1 struct{}

func NewV1() seller.ISellerV1 {
	return &ControllerV1{}
}
