// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package portal

import (
	"gitee.com/gosoft/gomall/internal/api/portal"
)

type ControllerV1 struct{}

func NewV1() portal.IPortalV1 {
	return &ControllerV1{}
}
