<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('systemAdmin/query', [\app\bundles\system\controller\SystemAdminController::class, 'query']);
    Route::post('systemAdmin/create', [\app\bundles\system\controller\SystemAdminController::class, 'create']);
    Route::get('systemAdmin/show', [\app\bundles\system\controller\SystemAdminController::class, 'show']);
    Route::put('systemAdmin/update', [\app\bundles\system\controller\SystemAdminController::class, 'update']);
    Route::delete('systemAdmin/destroy', [\app\bundles\system\controller\SystemAdminController::class, 'destroy']);
    Route::post('systemAdminRole/query', [\app\bundles\system\controller\SystemAdminRoleController::class, 'query']);
    Route::post('systemAdminRole/create', [\app\bundles\system\controller\SystemAdminRoleController::class, 'create']);
    Route::get('systemAdminRole/show', [\app\bundles\system\controller\SystemAdminRoleController::class, 'show']);
    Route::put('systemAdminRole/update', [\app\bundles\system\controller\SystemAdminRoleController::class, 'update']);
    Route::delete('systemAdminRole/destroy', [\app\bundles\system\controller\SystemAdminRoleController::class, 'destroy']);
    Route::post('systemMenu/query', [\app\bundles\system\controller\SystemMenuController::class, 'query']);
    Route::post('systemMenu/create', [\app\bundles\system\controller\SystemMenuController::class, 'create']);
    Route::get('systemMenu/show', [\app\bundles\system\controller\SystemMenuController::class, 'show']);
    Route::put('systemMenu/update', [\app\bundles\system\controller\SystemMenuController::class, 'update']);
    Route::delete('systemMenu/destroy', [\app\bundles\system\controller\SystemMenuController::class, 'destroy']);
    Route::post('systemPermission/query', [\app\bundles\system\controller\SystemPermissionController::class, 'query']);
    Route::post('systemPermission/create', [\app\bundles\system\controller\SystemPermissionController::class, 'create']);
    Route::get('systemPermission/show', [\app\bundles\system\controller\SystemPermissionController::class, 'show']);
    Route::put('systemPermission/update', [\app\bundles\system\controller\SystemPermissionController::class, 'update']);
    Route::delete('systemPermission/destroy', [\app\bundles\system\controller\SystemPermissionController::class, 'destroy']);
    Route::post('systemRole/query', [\app\bundles\system\controller\SystemRoleController::class, 'query']);
    Route::post('systemRole/create', [\app\bundles\system\controller\SystemRoleController::class, 'create']);
    Route::get('systemRole/show', [\app\bundles\system\controller\SystemRoleController::class, 'show']);
    Route::put('systemRole/update', [\app\bundles\system\controller\SystemRoleController::class, 'update']);
    Route::delete('systemRole/destroy', [\app\bundles\system\controller\SystemRoleController::class, 'destroy']);
    Route::post('systemRolePermission/query', [\app\bundles\system\controller\SystemRolePermissionController::class, 'query']);
    Route::post('systemRolePermission/create', [\app\bundles\system\controller\SystemRolePermissionController::class, 'create']);
    Route::get('systemRolePermission/show', [\app\bundles\system\controller\SystemRolePermissionController::class, 'show']);
    Route::put('systemRolePermission/update', [\app\bundles\system\controller\SystemRolePermissionController::class, 'update']);
    Route::delete('systemRolePermission/destroy', [\app\bundles\system\controller\SystemRolePermissionController::class, 'destroy']);
});
