<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('banner/query', [\app\bundles\banner\controller\BannerController::class, 'query']);
    Route::post('banner/create', [\app\bundles\banner\controller\BannerController::class, 'create']);
    Route::get('banner/show', [\app\bundles\banner\controller\BannerController::class, 'show']);
    Route::put('banner/update', [\app\bundles\banner\controller\BannerController::class, 'update']);
    Route::delete('banner/destroy', [\app\bundles\banner\controller\BannerController::class, 'destroy']);
    Route::post('bannerPosition/query', [\app\bundles\banner\controller\BannerPositionController::class, 'query']);
    Route::post('bannerPosition/create', [\app\bundles\banner\controller\BannerPositionController::class, 'create']);
    Route::get('bannerPosition/show', [\app\bundles\banner\controller\BannerPositionController::class, 'show']);
    Route::put('bannerPosition/update', [\app\bundles\banner\controller\BannerPositionController::class, 'update']);
    Route::delete('bannerPosition/destroy', [\app\bundles\banner\controller\BannerPositionController::class, 'destroy']);
});
