<?php

declare(strict_types=1);

namespace app\bundles\user\request\user;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'UserUpdateRequest',
    required: [
        'id',
        'username',
        'password',
        'nickname',
        'real_name',
        'avatar',
        'mobile',
        'email',
        'gender',
        'birthday',
        'province',
        'city',
        'district',
        'address',
        'id_card',
        'bio',
        'points',
        'balance',
        'level',
        'status',
        'register_ip',
        'last_login_ip',
        'last_login_time',
        'is_verified',
        'email_verified',
        'mobile_verified',
        'openid',
        'unionid',
        'extra_data',
        'deleted',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: 'ID', type: 'integer'),
        new OA\Property(property: 'username', description: '用户名', type: 'string'),
        new OA\Property(property: 'password', description: '登录密码', type: 'string'),
        new OA\Property(property: 'nickname', description: '昵称', type: 'string'),
        new OA\Property(property: 'real_name', description: '真实姓名', type: 'string'),
        new OA\Property(property: 'avatar', description: '头像', type: 'string'),
        new OA\Property(property: 'mobile', description: '手机号码', type: 'string'),
        new OA\Property(property: 'email', description: '电子邮箱', type: 'string'),
        new OA\Property(property: 'gender', description: '性别: 0-未知;1-男;2-女', type: 'integer'),
        new OA\Property(property: 'birthday', description: '生日', type: 'string'),
        new OA\Property(property: 'province', description: '省份', type: 'string'),
        new OA\Property(property: 'city', description: '城市', type: 'string'),
        new OA\Property(property: 'district', description: '区县', type: 'string'),
        new OA\Property(property: 'address', description: '详细地址', type: 'string'),
        new OA\Property(property: 'id_card', description: '身份证号', type: 'string'),
        new OA\Property(property: 'bio', description: '个人简介', type: 'string'),
        new OA\Property(property: 'points', description: '积分', type: 'integer'),
        new OA\Property(property: 'balance', description: '余额', type: 'float'),
        new OA\Property(property: 'level', description: '用户等级', type: 'integer'),
        new OA\Property(property: 'status', description: '状态: 1-正常;2-禁用;3-冻结', type: 'integer'),
        new OA\Property(property: 'register_ip', description: '注册IP', type: 'string'),
        new OA\Property(property: 'last_login_ip', description: '最后登录IP', type: 'string'),
        new OA\Property(property: 'last_login_time', description: '最后登录时间', type: 'string'),
        new OA\Property(property: 'is_verified', description: '是否实名认证: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'email_verified', description: '邮箱是否验证: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'mobile_verified', description: '手机是否验证: 0-否;1-是', type: 'integer'),
        new OA\Property(property: 'openid', description: '微信OpenID', type: 'string'),
        new OA\Property(property: 'unionid', description: '微信UnionID', type: 'string'),
        new OA\Property(property: 'extra_data', description: '扩展数据(JSON)', type: 'string'),
        new OA\Property(property: 'deleted', description: '删除状态: 0-未删除;1-已删除', type: 'integer'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class UserUpdateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'username' => 'require',
        'password' => 'require',
        'nickname' => 'require',
        'real_name' => 'require',
        'avatar' => 'require',
        'mobile' => 'require',
        'email' => 'require',
        'gender' => 'require',
        'birthday' => 'require',
        'province' => 'require',
        'city' => 'require',
        'district' => 'require',
        'address' => 'require',
        'id_card' => 'require',
        'bio' => 'require',
        'points' => 'require',
        'balance' => 'require',
        'level' => 'require',
        'status' => 'require',
        'register_ip' => 'require',
        'last_login_ip' => 'require',
        'last_login_time' => 'require',
        'is_verified' => 'require',
        'email_verified' => 'require',
        'mobile_verified' => 'require',
        'openid' => 'require',
        'unionid' => 'require',
        'extra_data' => 'require',
        'deleted' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置ID',
        'username.require' => '请设置用户名',
        'password.require' => '请设置登录密码',
        'nickname.require' => '请设置昵称',
        'real_name.require' => '请设置真实姓名',
        'avatar.require' => '请设置头像',
        'mobile.require' => '请设置手机号码',
        'email.require' => '请设置电子邮箱',
        'gender.require' => '请设置性别: 0-未知;1-男;2-女',
        'birthday.require' => '请设置生日',
        'province.require' => '请设置省份',
        'city.require' => '请设置城市',
        'district.require' => '请设置区县',
        'address.require' => '请设置详细地址',
        'id_card.require' => '请设置身份证号',
        'bio.require' => '请设置个人简介',
        'points.require' => '请设置积分',
        'balance.require' => '请设置余额',
        'level.require' => '请设置用户等级',
        'status.require' => '请设置状态: 1-正常;2-禁用;3-冻结',
        'register_ip.require' => '请设置注册IP',
        'last_login_ip.require' => '请设置最后登录IP',
        'last_login_time.require' => '请设置最后登录时间',
        'is_verified.require' => '请设置是否实名认证: 0-否;1-是',
        'email_verified.require' => '请设置邮箱是否验证: 0-否;1-是',
        'mobile_verified.require' => '请设置手机是否验证: 0-否;1-是',
        'openid.require' => '请设置微信OpenID',
        'unionid.require' => '请设置微信UnionID',
        'extra_data.require' => '请设置扩展数据(JSON)',
        'deleted.require' => '请设置删除状态: 0-未删除;1-已删除',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
