// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package market

import (
	"gitee.com/gosoft/gomall/internal/app/market"
)

type ControllerV1 struct{}

func NewV1() market.IMarketV1 {
	return &ControllerV1{}
}
