<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group(function () {
    Route::post('setting/query', [\app\bundles\setting\controller\SettingController::class, 'query']);
    Route::post('setting/create', [\app\bundles\setting\controller\SettingController::class, 'create']);
    Route::get('setting/show', [\app\bundles\setting\controller\SettingController::class, 'show']);
    Route::put('setting/update', [\app\bundles\setting\controller\SettingController::class, 'update']);
    Route::delete('setting/destroy', [\app\bundles\setting\controller\SettingController::class, 'destroy']);
});
