// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package console

import (
	"gitee.com/gosoft/gomall/internal/api/console"
)

type ControllerV1 struct{}

func NewV1() console.IConsoleV1 {
	return &ControllerV1{}
}
