// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package shop

import (
	"gitee.com/gosoft/gomall/internal/app/shop"
)

type ControllerV1 struct{}

func NewV1() shop.IShopV1 {
	return &ControllerV1{}
}
