<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('portal', function () {
    Route::get('home', [\app\api\portal\controller\IndexController::class, 'index']);
});
